language: generic
sodu: required
services:
  - docker

before_install:
  - docker build -f dockerfile.dev -t shivanshverma/react-nginx .

script:
  - docker run -e CI=true shivanshverma/react-nginx npm run test
# deploy:
#   provider: elasticbeanstalk
#   region: "us-west-2"
#   app: "docker"
#   env: "Docker-env"
#   bucket_name: "elasticbeanstalk-us-west-2-{id}"
#   bucket_path: "docker"
#   on:
#     branch: "master"
